services:
  - type: web
    name: onboardai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd rag_app/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDirectory: .